platform :ios, '9.0'

target 'Audimojis' do
  use_frameworks!
  pod 'MessageKit', :path => '../'

target 'AudimojisTests' do
  inherit! :search_paths
end

target 'AudimojisUITests' do
  inherit! :search_paths
end

end
